version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-rate-limiter
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-rate-limiter
    ports:
      - "3000:3000"