spring:
  application:
    name: ratelimiter

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  
rate-limiter:
  capacity: 3
  refill-rate: 0.0005
  window-length: 10000
  algorithm: SLIDING_WINDOW

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  endpoint:
    health:
      show-details: always